WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE WHERE HOUR < 23
)

SELECT 
    H.HOUR, 
    COUNT(A.ANIMAL_ID) AS COUNT
FROM 
    TIME_TABLE H
LEFT JOIN 
    ANIMAL_OUTS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY 
    H.HOUR
ORDER BY 
    H.HOUR;
