WITH S AS (
  SELECT g.EMP_NO,
         SUM(g.SCORE) AS SCORE
  FROM HR_GRADE g
  WHERE g.YEAR = 2022
  GROUP BY g.EMP_NO
),
MAX_SCORE AS (
  SELECT MAX(SCORE) AS MAX_SCORE
  FROM S
)
SELECT
  S.SCORE,
  E.EMP_NO,
  E.EMP_NAME,
  E.POSITION,
  E.EMAIL
FROM S
JOIN MAX_SCORE M
  ON S.SCORE = M.MAX_SCORE
JOIN HR_EMPLOYEES E
  ON E.EMP_NO = S.EMP_NO;