SELECT f.CATEGORY,
       m.MAX_PRICE,
       f.PRODUCT_NAME
FROM FOOD_PRODUCT AS f
JOIN (
  SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
  FROM FOOD_PRODUCT
  WHERE CATEGORY IN ('식용유', '과자', '국', '김치')
  GROUP BY CATEGORY
) AS m
  ON f.CATEGORY = m.CATEGORY
 AND f.PRICE    = m.MAX_PRICE
ORDER BY m.MAX_PRICE DESC;